### ISSUE TITLE
Implement Welcome page - mobile version - loading screen animation

### ISSUE THREAD

**Issue by davide2894** [davide2894/Memento#2]
Translate in SCSS (you can use CSS syntax) the loading screen in the Welcome page mockup that you can find [**here**](https://github.com/davide2894/Memento/blob/master/Web%20design/Mockup__Mobile__welcome-page.png)

It should be something like [**this codepen**](https://codepen.io/jasondavis/pen/XJMvZg)

You can write your code in: 
* src/index.html
* src/_sass/_welcome.scss

Please post below your codepen BEFORE making a pull request.
Please make sure to use CSS GRID and/or FLEXBOX.

**Comment by lybhy** [comment]
I would like to do this

**Comment by davide2894** [comment]
ok :smile:

**Comment by davide2894** [comment]
Thank you for your contribution! Merged :)
