### ISSUE TITLE
Create Memento SVG logo

### ISSUE THREAD

**Issue by davide2894** [davide2894/Memento#4]
Create an SVG logo for Memento to use for Mobile and Desktop versions, based on the mockup [**here**](https://github.com/davide2894/Memento/blob/master/Web%20design/Mockup__Mobile__welcome-page.png)

Please post it below BEFORE making a pull request.

**Comment by JakeShelterwin** [comment]
Ok, i'll be in charge of this :)

**Comment by davide2894** [comment]
Ok :smile:
