### ISSUE TITLE
Implement page: Write Memory - mobile version

### ISSUE THREAD

**Issue by davide2894** [davide2894/Memento#7]
Translate in SCSS (you can use CSS syntax) the mockup of "Write Memory" page that you can find [**here**](https://github.com/davide2894/Memento/blob/master/Web%20design/Mockup__Mobile__write-memory.png)

You can write your code:
* here for the page structure: [https://github.com/davide2894/Memento/blob/master/src/user-write-memories.html](https://github.com/davide2894/Memento/blob/master/src/user-write-memories.html)
* here for the page style: [https://github.com/davide2894/Memento/blob/master/src/_sass/_user-page-write-memories.scss](https://github.com/davide2894/Memento/blob/master/src/_sass/_user-page-write-memories.scss)

Please post below your codepen BEFORE making a pull request.
Please make sure to use CSS GRID and/or FLEXBOX.

**Comment by lybhy** [comment]
I can try if you want 😄

**Comment by davide2894** [comment]
ok :)
